"""add report & moderation to item & user

Revision ID: 2a147ddfa3ed
Revises: 0313549d9e24
Create Date: 2025-12-30 17:11:28.847988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2a147ddfa3ed'
down_revision: Union[str, Sequence[str], None] = '0313549d9e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('is_hidden', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('items', sa.Column('hidden_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('warning_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('ban_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('ban_until', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_is_banned'), 'users', ['is_banned'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_banned'), table_name='users')
    op.drop_column('users', 'ban_until')
    op.drop_column('users', 'ban_reason')
    op.drop_column('users', 'is_banned')
    op.drop_column('users', 'warning_count')
    op.drop_column('items', 'hidden_reason')
    op.drop_column('items', 'is_hidden')
    # ### end Alembic commands ###
