"""rename pfp to image in users table

Revision ID: 8972a1c95bd8
Revises: 2eb73e0762dd
Create Date: 2025-12-05 12:36:13.675540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8972a1c95bd8'
down_revision: Union[str, Sequence[str], None] = '2eb73e0762dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("image", sa.String(), nullable=True))
    op.execute("UPDATE users SET image = profile_picture")
    op.alter_column("users", "image", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # 1. Add old column back as nullable
    op.add_column(
        "users",
        sa.Column("profile_picture", sa.String(), nullable=True)
    )

    # 2. Copy image → profile_picture
    op.execute("UPDATE users SET profile_picture = image")

    # 3. Make it NOT NULL (only after backfilling)
    op.alter_column("users", "profile_picture", nullable=False)

    # 4. Drop the new column
    op.drop_column("users", "image")
